### ISSUE TITLE
Use RabbitMQ + dramatiq for queue persistence

### ISSUE THREAD

**Issue by asdfMaciej** [emigracja/app#83]
# RabbitMQ + Dramatiq

We should use RabbitMQ + dramatiq as our asynchronic backend for news processing.

## Reasoning 

It provides persistence in case of unexpected application restarts. It also allows the application to handle burst traffic, which often happens when the backend sends a batch of news to the AI module.

## Implementation details

We should create 2 queues for:

1. Processing news
2. Notifying the backend

### Processing news

Up to 1 retry after a 1 minute delay. 

### Notifying the backend

Up to 2 retries after (approx) 1 minutes and 5 minutes.

### Reasoning

For our basic purpose, we don't need the queues to be highly resistant to failure. This could be tweaked to different settings for a production environment, but for local development, those defaults are perfectly fine.

## Deployment details

The RabbitMQ queues should use the quorum type, as they're durable. This should be solved by creating a `rabbitmq.conf` file with the setting:

```
default_queue_type = quorum
```

We must install dramatiq with rabbitmq using poetry in container:

```
poetry add "dramatiq[rabbitmq, watch]"
```

The docker compose should include rabbitmq:

```
rabbitmq:
    image: rabbitmq:4-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./ai/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
```

The docker compose should launch additional worker. The current configuration for `ai` module is as follows:

```yaml
services:
  ai:
    build:
      context: ai
      dockerfile: Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - NEWS_IMPACT_LLM=${NEWS_IMPACT_LLM}
      - COMMAND_PARSE_LLM=${COMMAND_PARSE_LLM}
      - BACKEND_API_URL=${BACKEND_API_URL}
      - MAXIMUM_STOCKS_TO_PROCESS_PER_ARTICLE=${MAXIMUM_STOCKS_TO_PROCESS_PER_ARTICLE}
      - NEWS_IMPACT_VARIANT=${NEWS_IMPACT_VARIANT}
    ports:
      - "5000:5000"
    volumes:
      - ./ai:/app
    networks:
      - tarantula
 ```

The configuration should be updated to something like:

```
worker:
    extends:
      service: ai
    command: dramatiq <correct-path> --processes 1 --threads 1
    # Could be modified due to poetry 
    # Dockerfile CMD for reference: CMD [ "poetry", "run", "python", "-m", "fastapi", "run", "--host", "0.0.0.0", "--port", "5000", "--reload"]
```

The 1 process / thread is currently deliberate, as we don't have rate limits configuret yet (this issue doesn't tackle that).
